version: '3.3'

volumes:
  postgres_data:

services:
  db:
    image: postgres:12.4
    container_name: postgresql
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    restart: always
  web:
    image: leomerzlyakov/yamdb_final:v1
    container_name: web_yamdb
    restart: always
    command: gunicorn api_yamdb.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db
    env_file:
      - ./.env
    volumes: 
      - ./static:/code/static
      - ./media:/code/media

  nginx:
    image: nginx:1.19.9-alpine
    container_name: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/var/www/django/static:ro
      - ./media:/var/www/django/media:ro
    ports:
      - "80:80"
    depends_on:
      - web